# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_1.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(603, 426)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("oil.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_4.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_4.addWidget(self.checkBox_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.toolButton = QtWidgets.QToolButton(self.tab)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_4.addWidget(self.toolButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit.setTabChangesFocus(True)
        self.textEdit.setAcceptRichText(False)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setMaxLength(32767)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.checkBox = QtWidgets.QCheckBox(self.tab)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.cnt = QtWidgets.QLabel(self.tab)
        self.cnt.setObjectName("cnt")
        self.horizontalLayout_2.addWidget(self.cnt)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 28))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setMinimumSize(QtCore.QSize(45, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox.setEditable(True)
        self.comboBox.setMaxVisibleItems(15)
        self.comboBox.setMinimumContentsLength(1)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.spinBox = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(256)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_3.addWidget(self.spinBox)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.Home = QtWidgets.QPushButton(self.tab_2)
        self.Home.setMaximumSize(QtCore.QSize(40, 16777215))
        self.Home.setObjectName("Home")
        self.horizontalLayout_3.addWidget(self.Home)
        self.PageUp = QtWidgets.QPushButton(self.tab_2)
        self.PageUp.setObjectName("PageUp")
        self.horizontalLayout_3.addWidget(self.PageUp)
        self.PageDown = QtWidgets.QPushButton(self.tab_2)
        self.PageDown.setObjectName("PageDown")
        self.horizontalLayout_3.addWidget(self.PageDown)
        self.End = QtWidgets.QPushButton(self.tab_2)
        self.End.setMaximumSize(QtCore.QSize(40, 16777215))
        self.End.setObjectName("End")
        self.horizontalLayout_3.addWidget(self.End)
        self.refreshButton = QtWidgets.QPushButton(self.tab_2)
        self.refreshButton.setMaximumSize(QtCore.QSize(45, 16777215))
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout_3.addWidget(self.refreshButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(3)
        self.textEdit.textChanged.connect(self.label_2.clear)
        self.checkBox_2.clicked.connect(self.textEdit.setFocus)
        self.checkBox_3.clicked.connect(self.textEdit.setFocus)
        self.toolButton.clicked.connect(self.textEdit.clear)
        self.pushButton_2.clicked.connect(MainWindow.close)
        self.PageDown.clicked.connect(self.spinBox.stepUp)
        self.PageUp.clicked.connect(self.spinBox.stepDown)
        self.lineEdit.returnPressed.connect(self.pushButton.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.textEdit, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.checkBox)
        MainWindow.setTabOrder(self.checkBox, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.tableWidget)
        MainWindow.setTabOrder(self.tableWidget, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.spinBox)
        MainWindow.setTabOrder(self.spinBox, self.Home)
        MainWindow.setTabOrder(self.Home, self.PageUp)
        MainWindow.setTabOrder(self.PageUp, self.PageDown)
        MainWindow.setTabOrder(self.PageDown, self.End)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "万金油客户端"))
        self.checkBox_2.setToolTip(_translate("MainWindow", "发布成功后自动清空文本"))
        self.checkBox_2.setText(_translate("MainWindow", "发布后清空文本"))
        self.checkBox_3.setToolTip(_translate("MainWindow", "自动获取剪贴板文本并覆盖原文本"))
        self.checkBox_3.setText(_translate("MainWindow", "监控剪贴板"))
        self.toolButton.setToolTip(_translate("MainWindow", "清空文本"))
        self.toolButton.setText(_translate("MainWindow", "╳"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "在这里编辑要发布的内容，按 Enter 换行，按 Ctrl+Enter 发布"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "在这里署名，按 Enter 发布"))
        self.checkBox.setText(_translate("MainWindow", "记住我"))
        self.label.setText(_translate("MainWindow", "字数统计"))
        self.cnt.setText(_translate("MainWindow", "0"))
        self.pushButton.setText(_translate("MainWindow", "发布"))
        self.pushButton_2.setText(_translate("MainWindow", "取消"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "发布"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "内容"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "发布者"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "发布时间"))
        self.label_4.setText(_translate("MainWindow", "共 0 条 每页"))
        self.comboBox.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "3"))
        self.comboBox.setItemText(2, _translate("MainWindow", "5"))
        self.comboBox.setItemText(3, _translate("MainWindow", "10"))
        self.comboBox.setItemText(4, _translate("MainWindow", "15"))
        self.comboBox.setItemText(5, _translate("MainWindow", "20"))
        self.comboBox.setItemText(6, _translate("MainWindow", "30"))
        self.comboBox.setItemText(7, _translate("MainWindow", "40"))
        self.comboBox.setItemText(8, _translate("MainWindow", "50"))
        self.comboBox.setItemText(9, _translate("MainWindow", "80"))
        self.comboBox.setItemText(10, _translate("MainWindow", "100"))
        self.label_5.setText(_translate("MainWindow", "条"))
        self.label_3.setText(_translate("MainWindow", "/1 页"))
        self.Home.setText(_translate("MainWindow", "首页"))
        self.PageUp.setText(_translate("MainWindow", "← 上一页"))
        self.PageDown.setText(_translate("MainWindow", "下一页 →"))
        self.End.setText(_translate("MainWindow", "末页"))
        self.refreshButton.setText(_translate("MainWindow", "刷新"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "浏览"))
